# Generated by Django 4.1 on 2022-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistcune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmywatchlist',
            name='release_date',
            field=models.TextField(),
        ),
    ]
