# Generated by Django 4.1 on 2022-11-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('multiimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addproducttest.multiimage')),
                ('id_toko', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('nama_produk', models.CharField(max_length=255)),
                ('kategori_produk', models.CharField(max_length=255)),
                ('harga_produk', models.IntegerField()),
                ('gambar_produk', models.ImageField(upload_to='')),
                ('deskripsi_produk', models.TextField(max_length=255)),
                ('link_produk', models.TextField()),
                ('is_valid', models.BooleanField()),
            ],
            bases=('addproducttest.multiimage',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproducttest.multiimage')),
            ],
        ),
    ]
