# Generated by Django 4.1 on 2022-11-23 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_barangmywatchlist_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmywatchlist',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='barangmywatchlist',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='barangmywatchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
